version: '3.8'

services:
  app:
    build: .
    container_name: sarhan_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/sarhan-indicators
      - JWT_SECRET=your-super-secret-jwt-key-change-this
      - JWT_EXPIRES_IN=30d
      - KASHIER_API_KEY=ff9f3ddb-7897-436c-84d7-6b8e920fd81c
      - KASHIER_SECRET_KEY=e2b7717e14a86661138c27ff552aa2a4$$f9ef3475c184e02bd0c284ba7e4c87b6466a62da1cd46474860f67bdf2baed3839dcbd793feabdd9ebd6ee3184aca323
      - KASHIER_MERCHANT_ID=MID-32839-729
      - KASHIER_MODE=test
      - BASE_URL=https://sarhanindicators.com
      - FRONTEND_URL=https://sarhanindicators.com
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: sarhan_mongo
    restart: always
    ports:
      - "27018:27017" # Changed host port to 27018 to avoid conflict with local mongod
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
